### ISSUE TITLE
schedulerjsTemplates

### ISSUE THREAD

**Issue by HanieHadadi** [magnusjt/schedulerjs#1]
when i download and open ex1.html file i face to this error 
ReferenceError: schedulerjsTemplates is not defined 
in schedular.js line 360 file
how can i fix it?

**Comment by HanieHadadi** [comment]
I found it . i dont know why when i download zip file this section of file doesnt download in my project 
var schedulerjsTemplates = (function() {

var t = {
  /\* jshint ignore:start */
  'layout' : ...
},
r = function(n) {
  var tn = t[n];
  return function(c, p, i) {
    return tn.render(c, p || t, i);
  };
};
return {
  'layout' : r('layout')
};
})();

**Comment by magnusjt** [comment]
It's because the example file uses the source versions. You'll have to run ´npm install´ and ´grunt´ to set everything up.
